---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - opensearch_install
    - opensearch_configure
    - opensearch_run

- import_tasks: preflight.yml
  tags:
    - opensearch_install
    - opensearch_configure
    - opensearch_run

- import_tasks: "{{ opensearch_action }}.yml"
  become: true

- name: Ensure opensearch is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: opensearch
    enabled: true
  tags:
    - opensearch_run
